version: '3.8'

services:
  cimut:
    image: cimutapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./src:/app/src"
    environment:
      - PYTHONUNBUFFERED=1